#+title: Pinebook Pro Troubleshooting Common Issues
#+categories: pinebook-pro
#+date: 2023-07-22 16:06:56-07:00
#+draft: false

* Pinebook Pro Troubleshooting Common Issues

** Preamble
A list of issues I've experienced first hand with the Pinebook Pro and
resolutions.

* Break/Fix
** Powerkey shuts off machine
The powerkey is not in the most ideal locations. Edit /etc/systemd/logind.conf
and change "HandlePowerKey=poweroff" to "HandlePowerKey=ignore"

** Can't boot at all after flashing EMMC
You could either use an emmc to usb adapter to reflash your EMMC (LAME).  You
could use your official pine64 UART cable to see if you could fix the problem
that way (EH).  The third option is that you carefully remove the pinebooks back
plate with the display opened.  It's important to open the display before
removing the back panel to prevent the flimsy plastic or chassis from cracking
(yup, that could happen).  Once opened, flip the emmc switch to disable the emmc
([[https://wiki.pine64.org/wiki/Pinebook_Pro#Key_Internal_Parts][reference]]).  With the laptop still open, begin the booting from your microsd.
Once you see the LED turn green, quickly flip the switch to turn on the emmc
again.  Since the EMMC is not present, the pinebook first boots from the
micro-sd.  Our goal is to turn on the EMMC early on in the kernel's boot up
phase, so this way the emmc gets recognized.  If you flip the switch to late,
the EMMC will not appear as a drive.  Once booted, you could either reflash a
new pinebook image or remove the bootloader from the emmc.

** Removing the bootloader
Uboot resides within the first 35 or so megabytes of the drive. This is why you
end up seeing free space preceding the boot partition of your drive. Without
this free space, uboot would be overwriting your bootfiles, so it's important
you add it if you're ever doing any manual partitioning (i.e installing Gentoo).
I'm including two methods. The first blindly overwrites the beginning of the
drive - potentially damaging the boot partition. The second specifically removes
the parts of the drive containing uboot, keeping your boot parition safe. If you
don't care about being able to boot from the emmc, use the first method.

#+begin_src shell
# I forgot how many megabytes of space uboot takes # Method 1
(destructive...maybe) dd if=/dev/zero of=/dev/BLKDEV bs=1M count=35 conv=fsync

# Method 2 (non-destructive) dd if=/dev/zero of=/dev/BLKDEV bs=32k seek=1
conv=fsync &>/dev/null dd if=/dev/zero of=/dev/BLKDEV bs=64k seek=128 conv=fsync
&>/dev/null dd if=/dev/zero of=/dev/BLKDEV bs=64k seek=192 conv=fsync
&>/dev/null
#+end_src

** Loose screws that fall out
Some people reported that their screws to the bottom plate would fall out after
sometime. I've never experienced this, but I still took the liberty of
preventing it from happening.  Go to the auto parts section of any store and get
yourself either low strength or medium strength threadlocker. Avoid getting high
strength threadlocker since you obviously still want to be able to easily
unscrew them in the future. Add that to your Pinebook Pro's screws and you're
good to go.  I used Permatex Threadlocker Blue (Medium Strength) 24200 which I
bought from Walmart. It works just fine.

** Blinking red light and not booting
Pretty sure this is indicative of a kernel panic. Nothing will be displayed on
the screen. The only way to tell what's going on is to use the UART cable for
the pinebook pro. Buy it if you don't have it. It's useful.

** Damaged thermal pad. Getting a replacement.
Purchase yourself a 4mm thermal pad from Amazon and you'll be all set.  Cut a 1
inch by 1 inch square.
