image: 
  name: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo --gc --baseURL https://writeonlyhugo.gitlab.io/writeonlyhugo-demo/
  artifacts:
    paths:
    - public
  only:
  - master

