relativeURLs = true
baseURL = "/"
title = "Queztaz"
author = "Queztaz"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

[params]
mainSections = ["blog"]
[markup.tableOfContents]
startLevel = 2
endLevel = 3
