baseURL: "https://www.fe00.xyz/"
theme: "writeonlyhugo-theme"
languageCode: "en-us"
title: "Peter's blog"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "FE00.xyz"
  description: "Peter's blog"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"

taxonomies:
  categories: "categories"
  series: "series"
  tags: "tags"
