#+title: Operazione: Vita Gentile
#+date: 2025-05-18T16:53:30-07:00
#+draft: false

* Operazione: Vita Gentile
** Preamble
General scratch buffer for offloading my brain. The contents do not aim to make
sense and they will be dynamically changing as time goes on.

** Life Style Changes
** Letter Mail
Mail sucks. I don't want or ask for any of it.

My letter mail is digitized and viewable through my web browser. I no longer
receive any physical mail to my address. The service used is US Global Mail. It
costs $30/month. Lettermail is scanned and downloadable as PDF

I don't need to worry about being at a particular place to view my mail. I am
free to go anywhere in the world without concern.

** Phone Number
We need phones for everything. I don't want to need a phone for something stupid
like a 2FA text. I'd rather use my computer for that. This system is pretty
sleek and saves me money and freedom. I'll articulate later : )

I ported my phone number to Google Voice. Now I have a reliable VOIP number. The
only thing my phone relies now is a web browser and internet connection. My
phone can have any data plan it wants. It could even be a data only sim and I
wouldn't notice the difference.

I have the freedom to remove phones from my life.

** Portable Computer System
I don't want to be reliant on having a "personal" computer. I want my computer
to be accessible everywhere I go.

I use my Android phone as a desktop through DexMode. With my work flow, it
functions the exact same a computer would. The phone connects via a USB-C dock
into a portable 1080P monitor. I enjoy the life proof case on it ¯\_(ツ)_/¯

I SSH into a remote box to runs my emacs elisp interpreter. This application has
simplified my entire digital workflow. All of my applications and platforms I
interface with can be done with emacs. This one application accounts for all the
software I use.

Instantly I can have the same browsing experience mirrored on any computer I
touch. I mostly use the Terminal extension for Google Chrome to connect. My
digital life has no dependencies, both physically and with software. I feel
really good about it. Zero stress or thought goes into how work.

** Moving to Cloud
I'm a simple person. I want my data to be easy to access in a way that's smart.

Google Workspace hosts my custom email and now all my file storage. I really
like how Gmail labels operate. The philosophy behind it makes sense, which is
becoming a more frequent of an experience using Google Products.

My files I can access offline using the Google Drive desktop client for
Windows. My document processing doesn't require another application be
installed. All my work is centralized in my web browser OR any remote terminal.

* Projects
** Privacy Computer
I used to use a Thinkpad X60 with Libreboot and a TTY only system. This was
painful. Web browsing was only done through TOR, mostly because Javascript would
peg the CPU.

I corebooted a Thinkpad X200 with disk encryptino. This can boot into a Tails
USB. I'd say this is a pretty simple setup with fantastic anonymity.
