#+title: Operazione: Vita Gentile
#+date: 2025-05-18T16:53:30-07:00
#+draft: false

* Operazione: Vita Gentile
** Preamble
This contains bits of my life I would rather not have saved in running memory. I
hope some of the things in this list can be inspiring or useful to you \()/

* Heading
** Phone
My cell phone number was ported to Google Voice to remove the dependence on my
phone. There is currently nothing on my device that can't be accessed from my
computer.

This provides the Freedom to have any cellular plan or provider I'd
like. Currently I pay $10 USD/month on US Mobile. The only thing I require is
cellular data.

** Post Mail
Postal mail is delivered to a Private Mail Box (PMB). All letter mail is
automatically digitized and viewable from a website.

The service I use is US Global Mail. The service costs $30/month and eliminates
the stupid letter-mail I receive. All that was required was a change of address
form be filled out with the US Postal Service.

I order packages using a different name to avoid those packages being delivered
to the remote address. I can use the Chrome "Secure Shell"

** Remote Shell Server Daily Driver
I SSH into a remote server running TMUX and Emacs. All the applications I use
I've built into Emacs. I love this system and it makes my digital life very
simplified.


I can use the Chrome "Secure Shell" extension to access my Emacs session
through my web browser. Copying to the clipboard is handled by using OSC escape
sequences via clipetty in Emacs.

** Portable Desktop
I don't want to be reliant on ANYTHING to be okay. Everything I can get rid of
or make more intuitive I will.

I only need SSH and any computer to be /at home/. It doesn't matter what I'm
wearing, where I am, the devices i have access to.

My phone I utilize as a tool. I have a portable monitor that runs DexMode. From
there I can access a fully functioning web browser (Brave) and terminal for SSH
(Terminus). I use a bluetooth portable keyboard. The entire system can be
powered from my one phone. I can still access my encrypted drives through my
USB-C doc and file manager.

** Anonymous Computer
I used to use a Librebooted FDE Thinkpad X60 as a daily driver. This sucked and
the only web browser that effectively worked was Tor+NoJS.

Now I daily drive a Thinkpad X220 with Coreboot. If I did want to be anonymous I
would use Tails Linux. Otherwise I would use Whonix or ordinary tor.

** Email Hosting/Cloud
I like Google! Mail labels are technologically a really nice way to lay my
emails out. All of my emails get physically stored in the Archive (folder for
unlabeled items). They then get labeled for the inbox and my other "folders". I
use filters to automatically label all different types of emails with color
coding.

I like the idea of my label views being nothing more than tags and queries. It
makes more sense than moving files between folders on a disk.

I've since moved all my files to Google Drive and integrated the calendar into
Emacs using the Google Calendar API and org-gcal packages.

** Note taking
I don't have good memory. My brain is an unsorted library and it performs just
well enough to recall patterns. All of the things I learn and feel I write down
into my org agenda. This integrates with my Google Calendar AND my Emacs email client.

Anything I can't risk keeping in RAM will be written to disk. High performance
brains with low capacities/optimizations need a lot of organizing to be okay : )
