---
title: "Getting the Default Wireless Password to TG1672G Routers"
date: 2023-12-16T14:09:06-06:00
draft: false
---


* Preface
Here in El Salvador, most houses that use TIGO as their ISP have the same ARRIS
TG1672G router. This router has a seemingly random password, but it actually
follows a pattern thats really easy to guess

* The Pattern

#+begin_src 
TG1672G<FIRST BYTE OF BSSID NIC SPECIFIC><LAST FOUR OF SSID>
#+end_src

* Getting the password
All we need is the BSSID of the WAP and the SSID. In my experience, its been the
case that every home has the same model modem. I'll assume its the same for you.

Without being connected to a wireless network, run the following in a Windows
Command Prompt as administrator.

#+begin_src
C:\windows\system32> netsh wlan show all

  SSID 20 : ARRIS-81A2
    Network type            : Infrastructure
    Authentication          : WPA2-Personal
    Encryption              : CCMP 
    BSSID 1                 : 98:6b:3d:61:81:a0
         Signal             : 24%  
         Radio type         : 802.11n
         Band               : 2.4 GHz
         Channel            : 1 
         Bss Load:
             Connected Stations:         0
             Channel Utilization:        35 (13 %)
             Medium Available Capacity:  31250 (1000000 us/s)
         Basic rates (Mbps) : 1 2 5.5 11
         Other rates (Mbps) : 6 9 12 18 24 36 48 54

#+end_src

That command will list out all local wireless networks. The first byte of the
NIC Specific is "61" and the last part of the password is final 4 of the SSID.

Putting it all together, the password will be ~TG1672G6181A2~

* Final Note
If this oversite doesn't get patched out in the feature, the only thing you may
have to change is the model number of the password.
