#+title: Pinebook Pro Use Nvme as Root
#+categories: pinebook-pro
#+date: 2023-07-22 16:02:57-07:00
#+draft: false

* Pinebook Pro Use Nvme as Root
** Preamble
Directions on using the Pinebook Pro's NVME as a root partition and the EMMC as

* Moving root partitions

** Assumptions
- You have an NVME drive installed and formatted with a single EXT4 partition
- Running Manjaro Arm or ALARM. Untested, though Debian may work the same as
  well. This process relies on the existence of ~/boot/extlinux/extlinux.conf~

** Mounting the system

#+begin_src shell
mount /dev/nvme0n1p1 /mnt
cd /mnt
mkdir dev sys proc mnt
#+end_src

** Copying root files

Use rsync to transfer the files. This excludes pseudo file systems.

#+begin_src shell
rsync -aHxv --numeric-ids --progress /* /mnt --exclude=/dev --exclude=/proc --exclude=/sys --exclude=/mnt
#+end_src

** Changing the root to nvme

Rename the boot folder which was copied to the NVME. This isn't needed. Edit
your extlinux.conf file on the EMMC, then change the setting for the root
partition path.

#+begin_src shell
$ mv /mnt/boot /mnt/boot.old
$ vim /boot/extlinux/extlinux.conf

# Change "root=LABEL=ROOT" to "root=/dev/nvme0n1p1"
#+end_src

*** Fix for read only boot partition error
If the boot partition is "read only", you can remount it with rw
permissions as so:

#+begin_src shell
$ mount /dev/mmcblk1p1 /boot -o remount,rw
#+end_src
